### ISSUE TITLE
Version 71.0.3578.80 affected the extension?

### ISSUE THREAD

**Issue by JeffKang** [jpablobr/simple-auto-scroll#14]
The extension seems to not work for me after this following:

Google Chrome is up to date
Version 71.0.3578.80 (Official Build) (64-bit)

Thanks for any information!

**Comment by jpablobr** [comment]
I think It should be fixed now. Feel free to re-open if still having issues.

**Comment by JeffKang** [comment]
Yep, all good.&nbsp; Thanks jpablobr.
