### ISSUE TITLE
Feature request: Time based scrolling

### ISSUE THREAD

**Issue by drwahl** [jpablobr/simple-auto-scroll#2]
I'd like to be able to set a time for how long it should take to get to the bottom of the page and have the extension automatically determine what scroll speed would be needed.

**Comment by jpablobr** [comment]
Just added the "enhancement" label to the issue. Still, doubt that any time soon I'll get to implement something like that. The only thing you can do ATM is modify the speed of the scroll in the settings/options page. Thanks for the suggestion, though.
