### ISSUE TITLE
Feature request: Infinite loop

### ISSUE THREAD

**Issue by YNedderhoff** [jpablobr/simple-auto-scroll#4]
I'd like to use this for a dashboard that doesn't fit on the screen. For that I'd need this extension to scroll in an infinite loop, meaning it scrolls down to the bottom, back up to the top, back to the bottom, and so on. Is that something that could be added as an option?

**Comment by jpablobr** [comment]
Just added the "enhancement" label to the issue. Still doubt, that any time soon, I'll get to implement something like that. Thanks for the suggestion, though.

**Comment by loretoparisi** [comment]
+1 that would be useful though!
