### ISSUE TITLE
not working with www.microsofttranslator.com

### ISSUE THREAD

**Issue by kajetan-mazur** [jpablobr/simple-auto-scroll#7]
Hello

I used to use microsoft word automatic translate option, and it worked fine. But from a few weeks whe i wanted to get all article translated i have to scroll it very very slow. So i tried using Your plugin, it works everywhere beside that website - how can we make it work there?

Best

**Comment by jpablobr** [comment]
I just tested it and it does seem to work as intended unless you meant this type of scrolling which isn't supported. 

https://github.com/jpablobr/simple-auto-scroll/issues/10
