### ISSUE TITLE
Feature Request: Hotkeys

### ISSUE THREAD

**Issue by felixbauerschaefer** [jpablobr/simple-auto-scroll#9]
Hi I'm guessing this was a short termed coding project. But if you revist it for one last revision upgrade would be great, as I think it works well just leaves out a desired feature to make it for me a good tool for recording. Which would be a hotkey option menu where you could say MOUSE4 for slow scrolling you get the idea.

Best regards
Felix

**Comment by jpablobr** [comment]
Just added the "enhancement" label to the issue. Still doubt, that any time soon, I'll get to implement something like that. Thanks for the suggestion, though.
